// <auto-generated />
namespace CSharpEgitimKampi301.DataAccsesLayer.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class mig1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(mig1));
        
        string IMigrationMetadata.Id
        {
            get { return "202411261231399_mig1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
